data:
  dir_img: './data/sirst/train/images'
  dir_mask: './data/sirst/train/masks'
  val_percent:  0.1
  mask_suffix: ''
  size: 128
  scale_input: 128
  interpolate_mode: bicubic

model:
  mode : 1
  n_channels: 3
  n_classes: 1
  layer: 4
  out_threshold: 0.5
  se: False
  load: False
  load_dir: ./checkpoint/
  save_dir: ./checkpoints/
  bilinear: True

trainer:
  batch_size: 8
  num_workers: 1
  epochs: 300
  learning_rate: 5e-6
  amp: True
  weight_decay: 1e-8
  momentum:  0.999
  gradient_clipping:  1.0
  FocalLoss : True

predict:
  pre_img: './data/sirst/test/images/'
  pre_mask: '.data/sirst/test/masks/'

#  load_dir: G:/mynet/code/outputs/2024-01-10/20-52-27/checkpoints/checkpoint_epoch142.pth
  load_dir: ./model/checkpoint_sirst.pth
  scale: 128
  mask_threshold: 0.5         # Minimum probability value to consider a mask pixel white
  classes: 1
  mask_suffix: ''
  batch_size: 1
  modelname: WSLCM
#  modelres: G:/mynet/comparison/cnn/MDvsFA_cGAN-master/pytorch_outputs/NUDT/results/
  modelres: G:/mynet/results/UIUNet/NUDT/

resizer:
  first_act: RE
  last_bn: True
  last_act: relu
  scale: 3
  mode: bicubic


hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
